import type { Metadata } from "next";
import { Geist, Geist_Mono, Vazirmatn } from "next/font/google";
import "./globals.css";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { LogoIcon } from "@/components/icons";
import { Header } from "@/components/ui/header";
import CustomCursor from "@/components/ui/custom-cursor";

const vazirmatn = Vazirmatn({
  subsets: ["arabic", "latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

const getDir = (locale: string): "ltr" | "rtl" => {
  const rtlLocale = "fa";
  return rtlLocale === locale ? "rtl" : "ltr";
};

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const dir = getDir(locale);

  return (
    <html lang={locale} dir={dir} className="h-full antialiased">
      <body className={`min-h-full flex flex-col ${vazirmatn.className}`}>
        <NextIntlClientProvider>
          <Header />
          {/* <CustomCursor /> */}
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
